cc_binary(
    name = "A1",
    srcs = [
        "A1.cc",
    ],
)

cc_binary(
    name = "A2",
    srcs = [
        "A2.cc",
    ],
)

cc_binary(
    name = "A3",
    srcs = [
        "A3.cc",
    ],
)

cc_binary(
    name = "A4",
    srcs = [
        "A4.cc",
    ],
)

cc_binary(
    name = "A5",
    srcs = [
        "A5.cc",
    ],
)

cc_binary(
    name = "B1",
    srcs = [
        "B1.cc",
    ],
)
